name: Demo Github Action

on:
  workflow_dispatch:

jobs:
  automation-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          scope: "@hitz-group"
      - name: Install dependencies
        run: |
          npm install
      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps
      - name: Install Cross Environment
        run: |
          npm install -g cross-env
      - name: Run Playwright tests
        run: |
          npm run test:prod
