name: Demo run Smoke Tests using Github Action

on:
  workflow_dispatch:

jobs:
  automation-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: |
          npm install
      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps
      - name: Install Cross Environment
        run: |
          npm install -g cross-env
      - name: Run Smoke Tests
        run: |
          npm run test:smoke
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: test-output/html/index.html
          retention-days: 30
